version: "3"

networks:
  mainNetwork:
    driver: bridge

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
        - mainNetwork
  db:
    image: postgres
    volumes:
        - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    networks:
        - mainNetwork
  frontend:
    environment:
         - REACT_APP_SERVER_URL=http://localhost:8088/backend
    image: pjanuszek/author-frontend
    ports:
        - 3000:3000
    stdin_open: true
    networks:
        - mainNetwork
  proxy:
    image: pjanuszek/author-proxy
    ports:
        - 8088:8088
    networks:
        - mainNetwork